[workspace]
subscription_id = "f6501a04-fd30-4396-8da3-3f471abb99e2"
resource_group_name = "tojohnjung-rg"
workspace_name = "advisorama"
storage_container_name = "pdf-brochures"
storage_uri = "abfs://pdf-brochures/turkey-hello.txt"

[compute.cpu]
name = "cpu-cluster"
size = "Standard_D2ds_v4"

[compute.gpu]
name = "gpu-cluster"
size = "Standard_NV12s_v3"
environment = "AzureML-ACPT-pytorch-1.12-py39-cuda11.6-gpu"

[job]
display_name = "new-bird-job"
command = "pip install -r requirements.txt && python app.py"
code_module_dir = "./fowl_classifier"