name: aml-cv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10.*
  - pip
  - pip:
    - azure-ai-ml
    - azure-identity
    - mlflow
    - numpy
    - pillow
    - tomli
    - torch
    - torchvision